version: '3'

services:
    api-demo:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PORT: 9001
                PROFILE: production
        ports:
          - "9001:9001"
